# 5.18 Numpy Arrays

In [42]:
import numpy as np

# Creating NumPy Arrays

In [43]:
grades = np.array([95,88,79,73,97,82])

In [44]:
grades

array([95, 88, 79, 73, 97, 82])

In [45]:
student = np.array(['Tom','Ann','Bill','Joe','Betty','Tim'])

In [46]:
student

array(['Tom', 'Ann', 'Bill', 'Joe', 'Betty', 'Tim'], dtype='<U5')

In [47]:
city_list = ['minneapolis','cleveland','alexandria']
city = np.array( city_list )

In [48]:
city

array(['minneapolis', 'cleveland', 'alexandria'], dtype='<U11')

### Creating NumPy Arrays with three lists

In [49]:
count_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [50]:
count_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [51]:
count  = np.array(count_list)

This is TWO dimensional Matrix x and y 

In [52]:
count

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Getting element in the Matrix

In [53]:
count[2,3]

12

The shape of this Matrix "count" is the number rows (3) and number of columns (4).   
In Matrix rows then columns is read so this "3 by 4 Matrix"
So there are TWO dimensions.       

In [54]:
count.shape

(3, 4)

Setting our dimensions of the NumPy Array.  

ndmin : int, optional    
Specifies the minimum number of dimensions that the resulting array should have.        
Ones will be pre-pended to the shape as needed to meet this requirement.      

In [55]:
small_count = np.array([1, 2, 3], ndmin=2)

In [56]:
small_count

array([[1, 2, 3]])

In [57]:
small_count.shape

(1, 3)

## Fast ways to generate NumPy arrays

In [59]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [61]:
np.zeros(3)

array([0., 0., 0.])

In [63]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])